project:
  type: website

website:
  title: "MA31007 Vector Calculus"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Unit 1: Basics (Weeks 1-2)"
        contents:
        - text: "Curves"
          href: curves.qmd
        - text: "Surfaces"
          href: surface.qmd
        - text: "Coordinate systems"
          href: coordinates.qmd
      - section: "Unit 2: Derivatives (Weeks 3-5)"
        contents:
        - text: "Derivatives of scalar fields"
          href: scalarfields.qmd
        - text: "Derivatives of vector fields"
          href: vectorfields.qmd
        - text: "Products & second derivatives"
          href: secondderivs.qmd
      - section: "Unit 3: Integrals (Weeks 6-8)"
        contents:
        - text: "Line integrals"
          href: lineintegrals.qmd
        - text: "Surface integrals"
          href: surfaceintegrals.qmd
        - text: "Volume integrals"
          href: volumeintegrals.qmd
      - section: "Unit 4: Theorems (Weeks 9-10)"
        contents:
        - text: "Stokes' theorem"
          href: stokes.qmd
        - text: "Divergence theorem"
          href: divergence.qmd
        - text: "Potentials"
          href: potentials.qmd
      - href: links.qmd

format:
  html:
    theme: cosmo
    toc: true