---
title: "Vector and scalar potentials"
---

::: {.hidden}
 \providecommand{\vv}[1]{{\mathbf{#1}}}
 \providecommand{\pd}[2]{{\frac{\partial #1}{\partial #2}}}
:::

The final part of our module concerns special types of vector fields.

We call a field $\vv{A}$ _solenoidal_ if
$$
\nabla\cdot \vv{A} = 0
$$
and we call a field $\vv{B}$ _irrotational_ if
$$
\nabla\times\vv{B} = \vv{0}.
$$

:::{.callout-note}
A field can be both solenoidal and irrotational, for example any constant field. But in general they are different things.
:::

## Irrotational fields
These are sometimes called _curl free_ fields, for obvious reasons. The key theorem is:

:::{.callout-important}
$$\nabla\times\vv{A} = \vv{0} \text{ if and only if }\vv{A} = \nabla \phi\text{ for some scalar field }\phi.$$
:::

We call $\phi$ a _scalar potential_ for $\vv{A}$. 

Proving $\impliedby$ is easy:
If $\vv{A} = \nabla \phi$ then
$$
\nabla\times \vv{A} = \nabla \times \nabla \phi = 0,
$$
this was one of our second derivative identities.

The proof in the other direction is much more complicated, but for any given example you can make it work.

### Example
Find a scalar potential for
$$
\vv{A} = [x^2,y^2,0].
$$

:::{.callout-tip collapse="true"}
## Solution
First check that $\nabla\times\vv{A}=\vv{0}$, otherwise it doesn't work.

Then we need to find $\phi$ such that $\nabla \phi = [x^2,y^2,0]$.

Maybe you can spot it directly, but otherwise we can break it down. We need to find $\phi(x,y,z)$ such that
$$
\begin{aligned}
\pd{\phi}{x} &= x^2,\qquad\text{(1)} \\
\pd{\phi}{y} &= y^2,\qquad\text{(2)}\\
\pd{\phi}{z} &= 0.\qquad\text{(3)}
\end{aligned}
$$

Integrating the (1), we have
$$\phi(x,y,z) = \frac{1}{3} x^3 + C_1(y,z)$$
Here $C_1$ is just a normal constant of integration, but because we integrated a partial derivative, this constant can depend on $y$ and $z$.

Then (2) becomes
$$\pd{C_1}{y} = y^2$$
so
$$
C_1 = \frac{1}{3} y^3 + C_2(z).$$
$C_1$ depends only on $y$ and $z$, so the new constant of integration $C_2$ depends only on $z$.
So we have
$$
\phi = \frac{1}{3}x^3 + \frac{1}{3}y^3 + C_2(z),
$$
so (3) gives
$$
\frac{dC_2}{dz} = 0
$$
so $C_2$ is just a constant.

So finally we have
$$
\phi(x,y,z) = \frac{1}{3}x^3 + \frac{1}{3}y^3 + C_2,
$$
where $C_2$ is any constant.
:::

:::{.callout-important}
Scalar potentials are not unique - you can add any constant to $\phi$ and it's still valid.
:::

## Solenoidal fields
These are also called _incompressible_ or _divergence free_^[In physics, the magnetic field is a solenoidal field. This is where the name comes from.]. The key theorem here is:

:::{.callout-important}
$$\nabla\cdot\vv{A} = \vv{0} \text{ if and only if }\vv{A} = \nabla\times \vv{B}\text{ for some vector field }\vv{B}.$$
:::

We call $\vv{B}$ a _vector potential_ for $\vv{A}$.
Again, you can easily prove that $\nabla\times\vv{B}$ is solenoidal, but the other way is harder. You can also easily prove this:

:::{.callout-important}
Vector potentials are not unique - If $\vv{B}$ is a vector potential for $\vv{A}$ then so is $\vv{B}+\nabla\phi$ for __any scalar field__ $\phi$.^[This is called _gauge freedom_ in physics.]
:::

This non-uniqueness is very important, because it means we can choose properties we want $\vv{B}$ to have. One convenient choice is often $$B_3=0,$$ no component in the $z$ direction.

### Example
Find a vector potential for
$$
\vv{A} = [x+y^2, -y+z^2, y^2]
$$

:::{.callout-tip collapse="true"}
## Solution
This works the same as for scalar potentials, but it gets much messier. I strongly recommend staring at it for 30 seconds to see if you can guess a potential that works, before trying as follows:

First, you could check it's actually solenoidal. That's quite quick in this case.

We need to find $\vv{B}=[B_1,B_2,B_3]$ such that
$$
[x+y^2, -y+z^2, y^2] = \nabla\times\vv{B} = [\pd{B_3}{y}-\pd{B_2}{z},\,\pd{B_1}{z}-\pd{B_3}{x},\,\pd{B_2}{x}-\pd{B_1}{y}].
$$

Let's make the gauge choice that $B_3=0$, so then we get
$$x+y^2 = -\pd{B_2}{z},$$
$$-y+z^2 = \pd{B_1}{z},$$
$$y^2 = \pd{B_2}{x} - \pd{B_1}{y}.$$

Integrating the first two of these, we have:
$$
B_2 = -x z - y^2 z + f(x, y)
$$
and
$$
B_1 = -y z + \frac{1}{3} z^3 + g(x, y)
$$
where $f$ and $g$ are some unknown integration constant functions.

Now, substitute $B_1$ and $B_2$ into the third equation:
$$
y^2 = (-z + \pd{f}{x}) - (-z + \pd{g}{y}) = \pd{f}{x} - \pd{g}{y}
$$

We still have some freedom here. A simple choice is $f(x, y) = 0$ and $g(x, y) = -\frac{1}{3} y^3$:
$$
\pd{f}{x} = 0,\quad \pd{g}{y} = -y^2
$$
So,
$$
y^2 = 0 - (-y^2) = y^2
$$
This works.

Therefore, a vector potential is:
$$
\vv{B} = \left[
	-y z + \frac{1}{3} z^3 - \frac{1}{3} y^3,\;
	-x z - y^2 z,\;
	0.
\right]
$$
:::

:::{.callout-tip}
As with many things in maths, finding the potentials is slow but checking they are valid is quick. Always check!
:::