---
title: "Derivatives of products and second derivatives"
---

::: {.hidden}
 \providecommand{\vv}[1]{{\mathbf{#1}}}
 \providecommand{\pd}[2]{{\frac{\partial #1}{\partial #2}}}
:::

This chapter focuses on certain identities we can derive by combining the different 3D derivatives. You should get used to using these identities, but you also need to be able to prove them from the definitions.

## Derivatives of products
You're familiar with the product rule for ordinary derivatives:
$$
\frac{d}{dx}(fg) = \frac{df}{dx}g + f\frac{dg}{dx}.
$$
How does this translate to our new grad, div and curl? The first thing to consider is what kinds of products we have.

**Think:** What possible products exist between any two of scalar fields $\phi$ and $\psi$ and vector fields $\vv{u}$ and $\vv{v}$, and is the result a scalar or vector field?

::: {.callout-tip collapse="true"}
## Solution
$\phi\psi$ is a scalar field

$\phi\vv{u}$ is a vector field

$\vv{u}\cdot\vv{v}$ is a scalar field

$\vv{u}\times\vv{v}$ is a vector field
:::

For each product which is a scalar we can work out a formula for the gradient^[You can do directional derivatives too but it's basically the same.], and for each vector we can work out formulas for the divergence and curl. Here is the list:

- Gradient of a product of scalars:
  $$
  \nabla(\phi\psi) = (\nabla\phi)\psi + \phi(\nabla\psi)
  $$
- Gradient of a dot product:
  $$
  \nabla(\vv{u}\cdot\vv{v}) = (\vv{u}\cdot\nabla)\vv{v} + (\vv{v}\cdot\nabla)\vv{u} + \vv{u}\times(\nabla\times\vv{v}) + \vv{v}\times(\nabla\times\vv{u})
  $$
- Divergence of a scalar times a vector:
  $$
  \nabla\cdot(\phi\vv{u}) = \vv{u}\cdot\nabla\phi + \phi\nabla\cdot\vv{u}
  $$
- Divergence of a cross product:
  $$
  \nabla\cdot(\vv{u}\times\vv{v}) = \vv{v}\cdot(\nabla\times\vv{u}) - \vv{u}\cdot(\nabla\times\vv{v})
  $$
- Curl of a scalar times a vector:
  $$
  \nabla\times(\phi\vv{u}) = (\nabla\phi)\times\vv{u} + \phi(\nabla\times\vv{u})
  $$
- Curl of a cross product:
  $$
  \nabla\times(\vv{u}\times\vv{v}) = \vv{u}(\nabla\cdot\vv{v}) - \vv{v}(\nabla\cdot\vv{u}) + (\vv{v}\cdot\nabla)\vv{u} - (\vv{u}\cdot\nabla)\vv{v}
  $$

### Example
For a general scalar field $\phi$ and vector field $\vv{u}$, show that
$$
\nabla \cdot \left(\phi\vv{u}\right) = \vv{u}\cdot \nabla \phi + \phi \nabla\cdot\vv{u}.
$$

::: {.callout-tip collapse="true"}
## Solution
Let $\phi$ be a scalar field and $\vv{u} = [u_1, u_2, u_3]$ a vector field. Then,
$$
\begin{aligned}
\nabla \cdot (\phi \vv{u}) &= \pd{}{x}(\phi u_1) + \pd{}{y}(\phi u_2) + \pd{}{z}(\phi u_3)\\
&= u_1 \pd{\phi}{x} + \phi \pd{u_1}{x} + u_2 \pd{\phi}{y} + \phi \pd{u_2}{y} + u_3 \pd{\phi}{z} + \phi \pd{u_3}{z}\\
&= u_1 \pd{\phi}{x} + u_2 \pd{\phi}{y} + u_3 \pd{\phi}{z} + \phi \left(\pd{u_1}{x} + \pd{u_2}{y} + \pd{u_3}{z}\right)\\
&= \vv{u} \cdot \nabla \phi + \phi (\nabla \cdot \vv{u}).
\end{aligned}
$$
:::

## Second derivatives
For normal derivatives, you know $\frac{d}{dx} \frac{dy}{dx} = \frac{d^2y}{dx^2}$ - this is basically just a definition.

In 3D, it's more complicated. Of course, we can only take the gradient of a scalar field, and only take the divergence or curl of a vector field so the possibilities are, for a vector field $\vv{u}$ and a scalar field $\phi$:

- $\nabla\cdot(\nabla\phi)$ gives a scalar field
- $\nabla\times(\nabla\phi)$ gives a vector field
- $\nabla (\nabla \cdot \vv{u})$ gives a vector field
- $\nabla \times(\nabla\times \vv{u})$ gives a vector field
- $\nabla \cdot(\nabla \times\vv{u})$ gives a scalar field

Any other combination, like $\nabla\cdot (\nabla \cdot \vv{u})$ is not defined.

Actually, there are two extra rules which you need to learn, and you can prove:
$$\nabla\cdot(\nabla \times \vv{u}) = 0$$
$$\nabla\times(\nabla \phi) = \vv{0}$$

### Example
For any scalar field $\phi$, show that $\nabla\times(\nabla \phi) = \vv{0}$.

::: {.callout-tip collapse="true"}
## Solution
$$
\begin{aligned}
\nabla\times(\nabla \phi) &= \nabla\times\left[\pd{\phi}{x},\,\pd{\phi}{y},\,\pd{\phi}{z},\,\right] \\
&= \left[ \pd{}{y}\pd{\phi}{z} - \pd{}{z}\pd{\phi}{y},\,\pd{}{z}\pd{\phi}{x} - \pd{}{x}\pd{\phi}{z},\,\pd{}{x}\pd{\phi}{y} - \pd{}{y}\pd{\phi}{x}\right] \\
&= \left[ \pd{}{y}\pd{\phi}{z} - \pd{}{y}\pd{\phi}{z},\,\pd{}{z}\pd{\phi}{x} - \pd{}{z}\pd{\phi}{x},\,\pd{}{x}\pd{\phi}{y} - \pd{}{x}\pd{\phi}{y}\right]  \\
&= \left[0,0,0\right]\\
&= \vv{0}.
\end{aligned}
$$
:::

::: {.callout-note}
The key with all of these proofs is the symmetry of a mixed partial derivatives, i.e. $\frac{\partial^2 f}{\partial x\partial y} = \frac{\partial^2 f}{\partial y\partial x}$^[Which holds as long as the second derivatives are continuous, which they always will be in this module.].
:::

## The Laplacian
The remaining three second derivatives, $\nabla\cdot(\nabla\phi)$, $\nabla \times(\nabla\times \vv{u})$ and $\nabla (\nabla \cdot \vv{u})$ are related to another operator called the _Laplacian_, which is given the symbol $\Delta$ or $\nabla^2$. We'll use $\Delta$ in this module.^[You won't get penalised if you prefer to write $\nabla^2$.]

For a scalar field $\phi$,
$$
\begin{aligned}
\nabla\cdot(\nabla\phi) &= \nabla\cdot\left[\pd{\phi}{x},\pd{\phi}{y},\pd{\phi}{z}\right] 
\\&= \pd{}{x}\pd{\phi}{x} + \pd{}{y}\pd{\phi}{y} + \pd{}{z}\pd{\phi}{z}
\\&= \frac{\partial^2 \phi}{\partial x^2} + \frac{\partial^2 \phi}{\partial y^2}+ \frac{\partial^2 \phi}{\partial z^2}
\end{aligned}
$$
This is what we define to be the $\Delta \phi$, the (scalar) Laplacian of $\phi$.

For a vector field $\vv{u}$,^[Try this as an exercise, it takes a while.]
$$
\begin{aligned}
\nabla(\nabla\cdot \vv{u}) - \nabla\times(\nabla\times\vv{u}) &= \left[\frac{\partial^2 u_1}{\partial x^2} + \frac{\partial^2 u_1}{\partial y^2}+ \frac{\partial^2 u_1}{\partial z^2},\,\frac{\partial^2 u_2}{\partial x^2} + \frac{\partial^2 u_2}{\partial y^2}+ \frac{\partial^2 u_2}{\partial z^2},\,\frac{\partial^2 u_3}{\partial x^2} + \frac{\partial^2 u_3}{\partial y^2}+ \frac{\partial^2 u_3}{\partial z^2}\right]\\
&= \left[\Delta u_1,\,\Delta u_2,\,\Delta u_3\right].
\end{aligned}
$$
This is what we define to be $\Delta \vv{u}$, the (vector) Laplacian of $\vv{u}$.

::: {.callout-important}
In Cartesians, the vector Laplacian is the scalar Laplacian of each of the components. In curvilinear co-ordinates, this isn't true.
:::