---
title: "Surface integrals"
---

::: {.hidden}
 \providecommand{\vv}[1]{{\mathbf{#1}}}
 \providecommand{\pd}[2]{{\frac{\partial #1}{\partial #2}}}
:::

# Preliminary: Multiple integrals
You may not have seen integrals before which look like this:
$$
\int_a^b dx \int_c^d dy\, f(x,y).
$$

:::{.callout-note}
Many people write these integrals as
$\int_a^b \int_c^d f(x,y)\, dx\, dy,$
or 
$\int_a^b \int_c^d f(x,y)\, dy\, dx$.
You may think that the elements $dx$ and $dy$ have to go on the right, but they don't. These notations don't make it clear which limits go with which integration, so I always write the elements on the left with the integral sign.
:::

To calculate these multiple integrals, you just have to do two normal integrals. Actually the order you do them in shouldn't matter, it's like a multiplication, but sometimes the limits of one depend on the other.

### Example
Calculate
$$
\int_0^1 dx \int_0^x dy (x^2y + 2y)
$$

::: {.callout-tip collapse="true"}
## Solution
The limits of the $y$ integral depend on $x$, so we need to do the $y$ integration first. We rewrite it as
$$
\int_0^1 dx \left(\int_0^x (x^2y + 2y) dy \right)
$$
The inner integral here is just a normal integration with respect to $y$. When we are integrating with respect to $y$, we just treat $x$ as a constant. So we have
$$
\int_0^1 dx \left(\int_0^x (x^2y + 2y) dy \right) = \int_0^1 dx \left[ \frac{1}{2} x^2 y^2 + y^2\right]_{y=0}^{y=x} = \int_0^1 dx \left[ \left(\frac{1}{2} x^4 + x^2\right) - \left(\frac{1}{2} x^2\cdot 0 + 0\right)\right].
$$
Now we just have one integration in $x$, which we know how to do
$$
\int_0^1 \left(\frac{1}{2} x^4 + x^2\right) dx = \left[\frac{1}{10}x^5 + \frac{1}{3}x^3\right]_0^1 = \frac{13}{30}.
$$
:::

# Surface integrals of scalar fields
$$
\int_S f(\vv{r}) dS
$$
There are two different $S$ symbols here, and they mean different things. $S$ is a surface, a particular object in space, but $dS$ is the general _surface area element_.
What this means is, add up lots of infinitely small bits of the surface, weighted by the function $f$.

The steps to do these integrals are exactly the same as the four steps we saw for line integrals, with two key differences: firstly, we will have to do a multiple integral, and secondly, we need to know that the surface area element is
$$dS = \left|\pd{\vv{r}}{u}\times\pd{\vv{r}}{v}\right|du\,dv$$
when the surface is parameterised by $u$ and $v$.

Why is it this? It's complicated, but we'll go through a derivation in class if we have time.

### Example
Calculate surface integral
$$
\int_S (x + 4xz)\, dS
$$
where $S$ is the surface $\{(x,y,z)\in\mathbb{R}^3\,|\,z=x^2,\,0\leq x\leq 1, 0\leq y\leq 1\}$.

::: {.callout-tip collapse="true"}
## Solution

Let's solve the surface integral step by step.

### Step 1: Parameterise the surface

The surface $S$ is given by $z = x^2$ for $0 \leq x \leq 1$, $0 \leq y \leq 1$.  The easiest way to parameterise this is to let $u=x$ and $v=y$. Then
$$
\vv{r}(u, u) = [u, v, u^2], \qquad 0 \leq u \leq 1,\ 0 \leq v \leq 1.
$$

### Step 2: Calculate $dS$

Compute the partial derivatives:
$$
\pd{\vv{r}}{u} = [1, 0, 2u], \qquad \pd{\vv{r}}{v} = [0, 1, 0]
$$
Take the cross product:
$$
\pd{\vv{r}}{u} \times \pd{\vv{r}}{v} = [-2u, 0, 1]
$$
The magnitude is:
$$
\left|[-2u, 0, 1]\right| = \sqrt{(-2u)^2 + 0^2 + 1^2} = \sqrt{4u^2 + 1}
$$
So,
$$
dS = \sqrt{4u^2 + 1}\ du\ dv
$$

### Step 3: Rewrite the integration

The function is $f(x, y, z) = x + 4xz = u + 4u^3$.

The surface integral becomes:
$$
\int_S (x^2 + z^2)\, dS = \int_0^1 du \int_0^1 dv\ (u + 4u^3)\ \sqrt{4u^2 + 1}
$$

### Step 4: Compute the answer
No $v$ appears in the integrand so this integral just simplifies to 1. We are left with
$$
\int_S (x^2 + z^2)\, dS = \int_0^1 (u + 4u^3)\ \sqrt{4u^2 + 1} \, du = \int_0^1 u(1+4u^2)^{3/2} \, du.
$$

By inspection, the integral is
$$
\int_0^1 u(1+4u^2)^{3/2} \, du = \left[\frac{1}{20}(1+4u^2)^{5/2}\right]_0^1 = \frac{5^{5/2}-1}{20}.
$$
:::

## Special case: surface area
As promised, we can now calculate the area of surfaces. This is simply the empty integral
$$
\int_S dS = \int du \int dv \left|\pd{\vv{r}}{u}\times\pd{\vv{r}}{v}\right|
$$

### Example: surface area of a sphere
Calculate the surface area of a sphere of radius $R$.

::: {.callout-tip collapse="true"}
## Solution
We're not told the exact surface, but let's assume the sphere is centred at the origin. 
Then we can parameterise by taking some inspiration from spherical polar co-ordinates:
$$[x,y,z] = [R\cos u\sin v,\,R\sin u\sin v,\,R\cos v], \qquad 0\leq u < 2\pi,\, 0\leq v\leq \pi.$$
This isn't exactly polar co-ordinates because $R$ is a constant not a variable, and $u$ and $v$ just parameterise the surface not the whole of 3D space.

Now we can just plug this into the formula above:
$$
\int_S dS = \int_0^{2\pi} du \int_0^{\pi} dv \left|[-R\sin u \sin v,\,R\cos u\sin v,\,0]\times[R\cos u\cos v,\,R\sin u\cos v,-R\sin v]\right|
$$
Pro-tip: take out as many factors from the cross product as you can before calculating it:
$$
\begin{aligned}
\int_S dS &= \int_0^{2\pi} du \int_0^{\pi} dv \left|R^2 \sin v\right|\cdot\left|[-\sin u,\,\cos u,\,0]\times[\cos u\cos v,\,\sin u\cos v,-\sin v]\right| \\
&= \int_0^{2\pi} du \int_0^{\pi} dv \left|R^2 \sin v\right|\cdot\left|[-\cos u \sin v,\,-\sin u\sin v,\,-\sin^2 u \cos v -\cos^2 u \cos v]\right| \\
&= \int_0^{2\pi} du \int_0^{\pi} dv \left|R^2 \sin v\right|\cdot\left|[\cos u \sin v,\,\sin u\sin v,\,\cos v]\right| \\
&= \int_0^{2\pi} du \int_0^{\pi} dv \left|R^2 \sin v\right|
\end{aligned}
$$
where we used the fact that $\left|[\cos u \sin v,\,\sin u\sin v,\,\cos v]\right| = 1$ (this is good to remember).

We don't need to worry about the absolute value of $\sin v$ because $v\in[0,\pi]$ where sine is non-negative. There is no $u$ in this expression so we can just mupltiply by $2\pi$ to give
$$
\begin{aligned}
\int_S dS = 2\pi R^2 \int_0^{\pi} dv \sin v = 2\pi R^2 [-\cos u]_0^{\pi} = 4\pi R^2.
\end{aligned}
$$
But you knew that already.
:::

# Flux integrals: surface integrals of vector fields
This integral has a special name and comes up a lot in physics. It is the rate at which a vector field 'goes through' a surface. 

:::{.callout-important}
Like line integrals of scalar fields, the __direction matters__. In this case, it is the direction of the normal (in or out, up or down, ...) which affects the sign of the final answer.
:::

There are two equivalent notations
$$
\int_S \vv{F}(\vv{r}) \cdot d\vv{S} = \int_S \vv{F}(\vv{r}) \cdot \hat\vv{n} dS
$$
and the second one gives a hint how to calculate these things: we define the _vector_ surface element $d\vv{S}$ in terms of the scalar element $dS$ as 
$$
d\vv{S} = \hat\vv{n} dS
$$
where $\hat\vv{n}$ is the unit normal to the surface.

For a parameterisation $(u,v)$, recall that the general normal is
$$
\vv{n}(u,v) = \frac{\partial\vv{r}}{\partial u} \times \frac{\partial\vv{r}}{\partial v}
$$
so the unit normal is
$$
\hat\vv{n}(u,v) = \frac{\frac{\partial\vv{r}}{\partial u} \times \frac{\partial\vv{r}}{\partial v}}{\left|\frac{\partial\vv{r}}{\partial u} \times \frac{\partial\vv{r}}{\partial v}\right|}
$$
and substituting $dS$, we can simplify to
$$
d\vv{S} = \hat\vv{n} dS = \frac{\partial\vv{r}}{\partial u} \times \frac{\partial\vv{r}}{\partial v} du\,dv.
$$

:::{.callout-tip}
Learn this last formula. The rest is really just derivation.
:::

### Example: Flux through a surface
Calculate the total flux of the vector field $\vv{F}(x,y,z) = [z^2,z,0]$ through the hemisphere $x^2+y^2+z^1=1$, $x\geq 0$, with an outward-facing normal.

#### Step 1: Parameterise the surface
The hemisphere means spherical co-ordinates seem natural here, as we can take $r=1$ and use
$$
[x,y,z] = [\cos u \sin v,\,\sin u \sin v,\,\cos v].
$$
We need to be careful here with the constraint that $x\geq 0$. With the usual limit for $v=\theta$, $0\leq v \leq \pi$, we know that $\sin v\geq 0$. 
So for $x\geq 0$ we just need $\cos u \geq 0$, so let's take $-\pi/2 \leq u \leq \pi/2$.

#### Step 2: Calculate $d\vv{S}$
Hopefully this is starting to become familiar:
$$
\begin{aligned}
d\vv{S} &= \pd{\vv{r}}{u} \times \pd{\vv{r}}{v} \\
&= [-\sin u \sin v,\,\cos u\sin v,\,0]\times[\cos u\cos v,\,\sin u\cos v,\,-\sin v]\\
&= \sin v\,[-\sin u,\,\cos u,\,0]\times[\cos u\cos v,\,\sin u\cos v,\,-\sin v]\\
&= \sin v\,[-\cos u \sin v,\,-\sin u\sin v,\,-\sin^2 u \cos v -\cos^2 u \cos v]\\
&= \sin v\,[-\cos u \sin v,\,-\sin u\sin v,\,-\cos v]
\end{aligned}
$$
We need to check this is the outward normal, as specified by the question. Actually this is $\sin v$ times $-\vv{r}$, so it's inward pointing!

Not to worry - we can just flip the signs:
$$d\vv{S} =  \sin v\,[\cos u \sin v,\,\sin u\sin v,\,\cos v]$$.

#### Step 3: Rewrite the integration
In our local co-ordinates,
$\vv{F}(u,v) = [z^2,z,0] = \cos v\,[\cos v,\,1,\,0]$ (remembering to take out the common factor), so the integral becomes
$$
\int_S \vv{F}\cdot d\vv{S} = \int_0^\pi dv \int_{-\pi/2}^{\pi/2} du \cos v[\cos v,\,1,\,0] \cdot \sin v\,[\cos u \sin v,\,\sin u\sin v,\,\cos v] = \int_0^\pi dv \int_{-\pi/2}^{\pi/2} du \sin v \cos v \left(\cos u \cos v \sin v + \sin u \sin v\right)
$$

#### Step 4: Compute the answer
Here it's the sum of two different things, so it's easiest to split it up:
$$\begin{aligned}\int_S \vv{F}\cdot d\vv{S} &= \int_0^\pi dv \int_{-\pi/2}^{\pi/2} du \left(\cos u \cos^2 v \sin^2 v + \sin u \cos v \sin^2 v\right)\\
&=\int_0^\pi dv \int_{-\pi/2}^{\pi/2} du\cos u \cos^2 v \sin^2 v + \int_0^\pi dv \int_{-\pi/2}^{\pi/2} du\sin u \cos v \sin^2 v.\end{aligned}$$

For both parts, the $u$ and $v$ integrals just separate into multiplication, giving
$$
\begin{aligned}
\int_0^\pi dv \int_{-\pi/2}^{\pi/2} du\cos u \cos^2 v \sin^2 v &= \left(\int_{-\pi/2}^{\pi/2} \cos u\,du\right)\left(\int_0^\pi \cos^2 v \sin^2 v\,dv\right) 
\\&= 2\left(\int_0^\pi \frac{1}{2}\sin^2 2v\,dv\right)
\\&= 2\times \frac{1}{4}
\\&= \frac{1}{2}.
\end{aligned}
$$
For the second part, note that $\int_{-\pi/2}^{\pi/2} \sin u\, du = 0$ (since sine is an odd function over a symmetric interval), so
$$
\int_0^\pi dv \int_{-\pi/2}^{\pi/2} du\sin u \cos v \sin^2 v = 0.
$$

Therefore, the total flux is $\frac{1}{2}$.

# Other surface integrals
Occasionally you might see things like
$$
\int_S \vv{F}(\vv{r}) \times d\vv{S}.
$$
This means exactly what you think: take the cross product with the surface normal instead of the dot product, so that the final answer is a vector instead of a scalar.